<a href="https://colab.research.google.com/github/Abishek92004/MyData/blob/main/NumpyTraining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print('a:\n',a)

a:
 [1 2 3 4]


In [17]:
np.random.randint(5)

0

In [19]:
b=np.array([[1,2],[3,4]])
print('b:\n',b)

b:
 [[1 2]
 [3 4]]


In [21]:
b.shape

(2, 2)

In [23]:
a.shape


(4,)

In [24]:
a=a.reshape(2,2)
print(a)

[[1 2]
 [3 4]]


In [28]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
zero_cols=np.zeros((5,))
zero_cols


array([0., 0., 0., 0., 0.])

In [39]:
one_cols=np.ones((5,2))
one_cols

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
np.column_stack((one_cols,zero_cols))

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])

In [43]:
a=np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
print(100 + a)

[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]]


In [45]:
print(2**a)

[[   1    2    4    8]
 [  16   32   64  128]
 [ 256  512 1024 2048]]


In [46]:
print(a**2)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [52]:
a = np.arange(1,21).reshape((4,5))
a = a*2
a

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [53]:
a>6

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [55]:
(a<3)|(a>8)

array([[ True, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [58]:
a=np.arange(1,6)
b=np.arange(6,11)
c=np.arange(11,16)
d=np.arange(16,21)
rstack=np.row_stack((a,b,c,d))
print(rstack*2)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


In [60]:
a=np.arange(20)
print(a[::5])

[ 0  5 10 15]


In [62]:
a[5:11]=-1
print(a)

[ 0  1  2  3  4 -1 -1 -1 -1 -1 -1 11 12 13 14 15 16 17 18 19]


In [63]:
a[[4,5,7]]

array([ 4, -1, -1])

In [66]:
c=np.arange(12).reshape((3,4))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
c[1,2]
c[1]

array([4, 5, 6, 7])

In [70]:
c[:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [71]:
c[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
c[:2,:3]

array([[0, 1, 2],
       [4, 5, 6]])

In [82]:
mat=np.arange(5,25).reshape((4,5))
mat=mat*2

In [83]:
mat[3]=np.array([1,2,3,4,5])
mat

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [ 1,  2,  3,  4,  5]])

In [85]:
a=np.array([1,2,3,4])
i=np.array([True,False,True,False])
a[i]

array([1, 3])

In [87]:
i=a>5
i

array([False, False, False, False])

In [88]:
names = np.array(["Cyrus", "Darius", "Xerxes"])
results = np.array([[17, 14], [20, 18], [13, 15]])
results

array([[17, 14],
       [20, 18],
       [13, 15]])

In [89]:
results[names=="Darius"]

array([[20, 18]])

In [92]:
a=np.random.randn(2,3)
a[a<0]=0
a

array([[0.36624858, 0.60808856, 0.        ],
       [0.12055902, 1.40202525, 0.        ]])

In [94]:
names = np.array(["Roxana", "Statira", "Roxana", "Statira", "Roxana"])
score = np.array([126, 115, 130, 141, 132])
score[score<130]

array([126, 115])

In [95]:
score[names=="Statira"]

array([115, 141])

In [101]:
score[names == "Roxana"] = score[names == "Roxana"] + 10
score

array([166, 125, 170, 151, 172])

In [104]:
x=np.random.choice(6,size=(2,4))
x

array([[0, 3, 4, 2],
       [0, 1, 2, 0]])

In [106]:
a=['a','b','c']
b=np.random.choice(a)
b

'a'

In [107]:
np.random.normal(1000, 100, size=10)

array([1080.70519156, 1214.18053841,  950.43818197, 1052.56374242,
        961.03535279, 1093.72964971,  918.30258006, 1101.96154396,
        965.85636744, 1075.12813991])

In [108]:
np.random.binomial(2, 0.5, size=(2,4))

array([[0, 1, 0, 2],
       [0, 1, 2, 2]])